Add ICC profile support for PSD input
OpenImageIO/oiio pull request #2788
Opened 2020-12-16 10:05 UTC by SRHMorris

## Description

Loads the icc profile from the file and adds it to the common specs.

## Checklist:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [ ] If this is more extensive than a small change to existing code, I
  have previously submitted a Contributor License Agreement
  ([individual](../src/doc/CLA-INDIVIDUAL), and if there is any way my
  employers might think my programming belongs to them, then also
  [corporate](../src/doc/CLA-CORPORATE)).
- [ ] I have updated the documentation, if applicable.
- [ ] I have ensured that the change is tested somewhere in the testsuite
  (adding new test cases if necessary).
- [x] My code follows the prevailing code style of this project.

2020-12-17 07:21 UTC, lgritz requested changes
This is great, thanks!

The CI tests are failing... but for the good reason! -- ICC profiles are being read now, and so the reference output on the "psd" testsuite entry is no longer matching. Can you please update the reference output?

The trick is that there are TWO reference output files -- testsuite/psd/ref/out.txt and out-alt.txt. They differ slightly because the exact values in the thumbnail seem to depend on libjpeg version, so there are two possible valid outputs! You'll have to update both, but only the line that changes because of ICC, please don't end up accidentally making those files the same in the ways that they are currently (and supposed to be) different. Sorry, that's a little confusing, I hope you know what I'm talking about.

There is an extremely minor code formatting fix needed that you can also see from the "clang-format" CI test.

2020-12-17 11:19 UTC, SRHMorris commented
Yeah I'd noticed that certain jpegs looked slightly different between libjpeg and libjpeg-turbo.

Don't think the last test is me!

2020-12-17 23:12 UTC, lgritz commented
No, that Mac failure is not you, something changed on the GitHub Mac instances (or on homebrew packaging), and I have a separate PR to address that. It looks like you've got everything passing now.

2020-12-18 20:23 UTC, lgritz approved these changes

2020-12-18 20:23 UTC, merged