RAW plugin improvements
OpenImageIO/oiio pull request #3045
Opened 2021-08-01 14:42 UTC by Shootfast

## Description

This PR introduces a number of fixes/updates for the RAW plugin.

1. It fixes the output when raw:Demosaic is set to "none". Previously pixel output was indexed incorrectly into the raw buffer and did not take into account rotation or possible "junk" pixels.
2. Implements raw:balance_clamped mode that will apply a per-channel clamp on all pixel values that are over the saturation level of the sensor. This eliminates issues where clipped highlights take on an unwanted hue shift. This is especially useful when stacking HDRI exposures.
3. Implements raw:apply_scene_linear_scale and raw:camera_to_scene_linear_scale, which allows users to scale libraw output to expected levels. The default scale factors are currently hard coded, but experimentally these settings have proven "good enough" over many years of use.

## Checklist:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] If this is more extensive than a small change to existing code, I
  have previously submitted a Contributor License Agreement
  ([individual](../src/doc/CLA-INDIVIDUAL), and if there is any way my
  employers might think my programming belongs to them, then also
  [corporate](../src/doc/CLA-CORPORATE)).
- [ ] I have updated the documentation, if applicable.
- [ ] I have ensured that the change is tested somewhere in the testsuite
  (adding new test cases if necessary).
- [x] My code follows the prevailing code style of this project.

2021-08-01 19:30 UTC, lgritz requested changes
Code LGTM other than the one problematic errorf call that I caught.

Needs clang-format (see log of the clang-format CI test). I can do that on my end if you want.

Output reference need updating, but I can add that myself as the last step.

2021-08-01 19:30 UTC, lgritz commented on src/raw.imageio/rawinput.cpp
> +                errorf(libraw_strerror(ret));
```suggestion
                errorf("%s", libraw_strerror(ret));
```

2021-08-01 20:00 UTC, lgritz commented
Also: would you mind adding any new configuration hints to the documentation in the RAW section of builtinplugins.rst? Thanks.

2021-08-02 15:45 UTC, Shootfast commented
Great, I'll update the docs and fix that error!

2021-08-14 04:40 UTC, lgritz commented
I pushed additions that fix the formatting and update the testsuite reference output.

2021-08-14 14:06 UTC, Shootfast commented
I've fixed the errorf calls and updated the docs

2021-08-14 17:46 UTC, lgritz commented
Thanks for adding the docs, this is fine and I'm ready to merge.

But just for my own edification, I'm a little confused about how these controls work and have a few questions. (Which may or may not prompt you to want to change something, it's up to you. I'm primarily indicating that I don't fully understand how these are used.)

1. If apply_scene_linear_scale merely enables the scale of camera_to_scene_linear_scale, why have two controls? Would it be simpler if camera_to_scene_linear_scale served both purposes, where it defaults to 1.0, in which case no scale is applied, and any other value both enables the scaling and also specifies the scale factor?
2. I wonder if the "changes output datatype to half" is confusing. A subsequent call to `read_scanlines()` et al still lets you ask for any data type you want. It may be that you are (internally) retrieving the data as half, but that's invisible to the user. Maybe it would be more clear if you said "enabling this option might result in pixel values that might be > 1.0, thus you should retrieve pixels as half or float values to ensure that values are not clipped by a data type conversion to integer types."

2021-08-14 17:49 UTC, lgritz approved these changes
LGTM, but I'll wait to merge until you see my minor questions, just in case they prompt you to want to change anything.

2021-08-14 20:09 UTC, Shootfast commented
>     1. If apply_scene_linear_scale merely enables the scale of camera_to_scene_linear_scale, why have two controls? Would it be simpler if camera_to_scene_linear_scale served both purposes, where it defaults to 1.0, in which case no scale is applied, and any other value both enables the scaling and also specifies the scale factor?

I am not expecting people to need to customize the scale value very frequently, nor expecting them to remember the magic number of 1.0 / 0.45. So I was planning on just saying "use apply_scene_linear_scale" in my general guidelines.
 
>     2. I wonder if the "changes output datatype to half" is confusing. A subsequent call to `read_scanlines()` et al still lets you ask for any data type you want. It may be that you are (internally) retrieving the data as half, but that's invisible to the user. Maybe it would be more clear if you said "enabling this option might result in pixel values that are > 1.0, thus you should retrieve pixels as half or float values to ensure that values are not clipped by a data type conversion to integer types."

Hmm, I'm not sure I think that's a good solution. The user doesn't choose the datatype of values that come out of the file per se, that is set by the plugin in the format (or per-channel format) of the spec. When a user asks for a specific datatype, the expectation is that the native type will be converted for them automagically. I would think that the ideal behavior would be that no data is lost by default, so changing the type returned by the plugin made the most sense. That way if you just go raw->exr (which I imagine is a very common use case) there is no loss.

I am open to any further discussion or feedback from the community before we merge this though.

2021-08-14 21:03 UTC, lgritz commented
> I am not expecting people to need to customize the scale value very frequently, nor expecting them to remember the magic number of 1.0 / 0.45. So I was planning on just saying "use apply_scene_linear_scale" in my general guidelines.

I see. So you are saying that it's two controls so that people can turn without needing to know what the magic value is for the common use case? Makes sense.


> Hmm, I'm not sure I think that's a good solution. The user doesn't choose the datatype of values that come out of the file per se, that is set by the plugin in the format (or per-channel format) of the spec. When a user asks for a specific datatype, the expectation is that the native type will be converted for them automagically. I would think that the ideal behavior would be that no data is lost by default, so changing the type returned by the plugin made the most sense. That way if you just go raw->exr (which I imagine is a very common use case) there is no loss.

Oh, I think I understand now. You're saying that if the options are used, the ImageSpec will report that the data is HALF, rather than uint16. I forgot that aspect of the situation. So it's not truly internal.

OK, all sounds fine to me.

2021-08-14 21:03 UTC, merged