[exif] Convert paramvalue string to integer when needed
OpenImageIO/oiio pull request #3886
Opened 2023-06-15 13:21 UTC by servantftechnicolor

Make sure we can input exif tags as strings containing numbers when number are required.

E.G. if my input is "Orientation"=>"8", i would like the jpeg output to contains the value 8 for the exif tag orientation.

2023-06-15 17:56 UTC, lgritz requested changes
I'm fine with the change generally, though I suggested a different idiom that avoids exceptions.

2023-06-16 05:26 UTC, servantftechnicolor commented on src/libOpenImageIO/exif.cpp
> +
Your wish is our command!

2023-06-16 18:04 UTC, lgritz commented on src/libOpenImageIO/exif.cpp
> +    }
Minor formatting fix according to CI clang-format:

```suggestion
    case TypeDesc::STRING: {
        if (Strutil::string_is_int(p.get_ustring())) {
            i = (T)p.get_int();
            break;
        } else {
            return false;
        }
    }
```

2023-06-16 20:40 UTC, lgritz approved these changes

2023-06-16 20:41 UTC, merged