Print build-time warnings for LGPL gotchas
OpenImageIO/oiio pull request #3958
Opened 2023-08-24 01:24 UTC by grdanny

Trying out my first Mackerel from:

https://github.com/OpenImageIO/oiio/issues/3916

2023-08-30 17:37 UTC, lgritz requested changes
I think you're on the right track to fully solve this issue. I recommended a few minor changes.

2023-08-30 17:37 UTC, lgritz commented on src/ffmpeg.imageio/CMakeLists.txt
> +   endif()
I like the approach. Danny, can you please clean up the indentation -- they don't always align, and some blocks intend 1 space, some 2, some 4? Let's use a consistent 4 like the rest of the cmake files.

2023-08-30 17:37 UTC, lgritz commented on src/heif.imageio/CMakeLists.txt
> +    endif ()
Can this be simplified? If you just do .lib and .a, and not need the `if`, so what? It won't find .lib in the libraries on non-Windows, so it doesn't hurt to search for it.

2023-08-30 17:37 UTC, lgritz commented on src/heif.imageio/CMakeLists.txt
> +     message(STATUS "When linking statically against a LGPL-licensed library your entire project needs to be under LGPL")
Let's omit the prescriptive legal advice and go with a simpler informational message that leaves the problem on their doorstep:

```
You are linking OpenImageIO against a static version of libheif, which is LGPL
licensed. If you intend to redistribute this build of OpenImageIO, we recommend
that you review the libheif license terms, or you may wish to switch to using a
dynamically-linked libheif.
```

I think this gives them the information they need to point them in the right direction, and avoids letting them stumble unaware into possible trouble, but without trying to tell them exactly what they can and can't do (which, as non-lawyers, we should not be doing and could be wrong about).

A slightly different message more accurately covers the ffmpeg situation:

```
You are linking OpenImageIO against a static version of FFmpeg, which may have
LGPL and possibly GPL licensed components (depending on exactly how your copy
of FFmpeg was built). If you intend to redistribute this build of OpenImageIO,
we recommend that you review the FFmpeg build flags and licensing terms.
```

2023-08-30 17:37 UTC, lgritz commented on src/ffmpeg.imageio/CMakeLists.txt
> +     message("${ColorRed}")
Let's use ColorYellow here. It's not a build break, just a warning.

2023-09-18 02:38 UTC, grdanny commented
This should be ready for review.
The only additional thought I had was maybe to turn this into a macro and share across the two cases (and maybe then it's useful in some other similar future case?)
But not sure if that is more helpful or confusing, right now it should be pretty clear why we added this.

2023-09-20 02:55 UTC, lgritz approved these changes

2023-09-20 02:56 UTC, lgritz commented
I think it's fine as it is, Danny. These are the only two instances of this that we know about. If another pops up, we can think about whether to refactor into some common infrastructure.

2023-09-20 02:57 UTC, lgritz commented
Fixes #3916

2023-09-20 03:13 UTC, merged